[profile.default]
evm_version = "cancun"
solc_version = "0.8.27"
verbosity = 2
libs = ["node_modules", "lib"]

[rpc_endpoints]
local = "${LOCAL_RPC_URL}"
upside = "${UPSIDE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# Uranium Finance
rw1 = "https://upside-chal.chainlight.io/rw1/rpc/oomia.dev:${UPSIDE_RPC_SIGNATURE}"

# Harvest Finance
rw2 = "https://upside-chal.chainlight.io/rw2/rpc/oomia.dev:${UPSIDE_RPC_SIGNATURE}"

# Fei Rari
rw3 = "https://upside-chal.chainlight.io/rw3/rpc/oomia.dev:${UPSIDE_RPC_SIGNATURE}"

# Superfluid
rw4 = "https://upside-chal.chainlight.io/rw4/rpc/oomia.dev:${UPSIDE_RPC_SIGNATURE}"

# Superfluid v2 (patched)
rw5 = "https://upside-chal.chainlight.io/rw5/rpc/oomia.dev:${UPSIDE_RPC_SIGNATURE}"


# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# https://book.getfoundry.sh/config/
# https://github.com/juanfranblanco/vscode-solidity?tab=readme-ov-file
# forge tree
# forge geiger
# forge coverage

[fmt]
sort_imports = true

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
